### ISSUE TITLE
KiCAD 6.99: Can't compress Gerber or SMT Assembly files

### ISSUE THREAD

**Issue by AiGreek** [Bouni/kicad-jlcpcb-tools#100]
Hiiiiiiii ^^'

Don't know why or when or how, but since the last update of Kicad Nightly (?) the plugin seems unable to zip or create the files for the SMT assemblies (BOM/POS). The logs do not seem to indicate any error whatsoever.

![image](https://user-images.githubusercontent.com/16197044/148688774-585f9520-9ccb-4fb9-b7c3-aff546d0cba2.png)

```
Application: KiCad PCB Editor (64-bit)

Version: (6.99.0-294-g04c46a8fd2), release build

Libraries:
	wxWidgets 3.1.5
	libcurl/7.78.0-DEV Schannel zlib/1.2.11

Platform: Windows 10 (build 19043), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jan  7 2022 21:00:04
	wxWidgets: 3.1.5 (wchar_t,wx containers)
	Boost: 1.76.0
	OCC: 7.5.0
	Curl: 7.78.0-DEV
	ngspice: 35
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

**Comment by Bouni** [comment]
I have not yet checked how the plugin is working with 6.99 so I concider it 6.0 only at the moment!

**Comment by Bouni** [comment]
I looked into this because I decided that (if possible) I want to support 6.0  as well as 6.99 becaus ein 6.99 a ton of cool feature land in the coming days an months.

I found that the API changed slightly in 6.99 and I check which version is running and use the right type (wxPoint vs. VECTOR2I) to avoid the problem.
