### ISSUE TITLE
Delete footprint(s), then Undo, erases LCSC part selection

### ISSUE THREAD

**Issue by boredbrain** [Bouni/kicad-jlcpcb-tools#151]
This is an issue in my case only because I often build more than one PCB for a product in the same Project/PCB file. This is because the boards mate together and share a schematic. So when I export Gerbers, I will simply select one of the boards, delete it, then export the other. After, I will Undo, delete the other one and export again. 

I can also imagine a situation where a part(s) is accidentally deleted and thus Undo is used. If this happened after LCSC part selection, you'd have to search and select again. Depending on the number of parts, it could be a big problem.

Thanks for your generous work on this!

**Comment by Bouni** [comment]
Hi,

this is a very special way of doing things ...

The problem is that the info what footprints are on the board is directly read from the `*.kicad_pcb` file.
The plugin stores the footprints into the `project.db` file when the plugin is started and deletes those from the database that are no longer on the board. So if you select a LCSC part for a footprint, that info is stored in the database as well.
Then you close the plugin, delete a footprint, start the plugin again and it will delete the just removed footprint as well as the LCSC info.

Changing the plugin in a way that supports your special workflow is a lot of work and I think I don't want to invest that time ...
If you come up with a PR that implements this and does not make the normal experiance worse I happily merge it.
