### ISSUE TITLE
No newer versions visible in KiCad Plugin and Content Manager

### ISSUE THREAD

**Issue by DomoticX** [Bouni/kicad-jlcpcb-tools#176]
Is it possible to add the newer versions/reases in the KiCad Plugin and Content Manager?

It saves time to manually upgrade ;-)

At the moment the older 2022.02.04 version in the latest in the list...

Kicad 6.0.5 / Win10 64-bit

![KiCadClipboardCM](https://user-images.githubusercontent.com/8792334/173183557-2476f361-99b8-43c4-a7f7-5f38089a002f.png)

**Comment by livigni** [comment]
if you go in the "Repository" tab and you select the Bouni's repository,
this will fetch new updates (so the list will show new versions too).
Still, unfortunately the plugin will not update somehow: you still need to
uninstall, apply changes and install the new version. Maybe because it is
"testing" version and not "stable"?

Il giorno sab 11 giu 2022 alle ore 12:12 DomoticX ***@***.***>
ha scritto:

**Comment by ayourk** [comment]
Kicad proper has plans on making this better in the future: https://gitlab.com/kicad/code/kicad/-/issues/11552

**Comment by Bouni** [comment]
@livigni and @ayourk nailed it, the only way to update is to first update the versions using the repository tab and then uninstall the old version and install the new version. Hopefully the KiCAD developers come up with a nice way of handling this soon.
Unfortunately there's nothing I can do about this for now, sorry 🤷🏽‍♂️
