### ISSUE TITLE
Sorting not quite working

### ISSUE THREAD

**Issue by arturo182** [Bouni/kicad-jlcpcb-tools#56]
Sorting by Reference doesn't work as expected, R10 is between R1 and R2, not after R9 as one would expect:
![image](https://user-images.githubusercontent.com/249082/138888072-aaec4311-d88b-4c5a-96e3-78e55b5b9a65.png)

Same for sorting by Stock, it just sorts by the first digit, not the actual number:
![image](https://user-images.githubusercontent.com/249082/138888161-f93ac0aa-eb00-42ec-83f2-6be267d83469.png)

**Comment by Bouni** [comment]
Just a quick update:

I added natural sort in the upcoming version that relies on sqlite instead of CSV and it seems to work as expected.

https://github.com/Bouni/kicad-jlcpcb-tools/blob/major-refactor/helpers.py#L16-L23
https://github.com/Bouni/kicad-jlcpcb-tools/blob/major-refactor/store.py#L55-L65

![image](https://user-images.githubusercontent.com/948965/141738208-27ab32e1-fa93-4a4b-81af-d4e34735b75e.png)

**Comment by bvernoux** [comment]
See my issue comment about that https://github.com/Bouni/kicad-jlcpcb-tools/discussions/74#discussioncomment-1705436

**Comment by Bouni** [comment]
@bvernoux Implemented in my latest commit to `major-refactor`

**Comment by Bouni** [comment]
Fixed in [2021.12.1](https://github.com/Bouni/kicad-jlcpcb-tools/tree/2021.12.1)
